### ISSUE TITLE
Add support for printing or generating a visual representation of the graph

### ISSUE THREAD

**Issue by Sphiinx** [anvaka/ngraph.graph#17]
Add support for printing or generating a visual representation of the graph to the console so you can visually see what the graph looks like and which nodes are linked to which. :D

**Comment by Sphiinx** [comment]
@anvaka Nevermind, I just found https://github.com/anvaka/VivaGraphJS 

Incredible work, it makes me appreciate graphs so much more (:

**Comment by anvaka** [comment]
Thanks! You can also check https://github.com/anvaka/graph-start - which gives a quick playground to work with graph algorithms
