### ISSUE TITLE
Finding total of linked nodes?

### ISSUE THREAD

**Issue by githubuser3141** [anvaka/ngraph.graph#18]
Sorry if this is outside the scope of the project, but could you advise on ways to find groups of linked nodes in the graph? I needed to count their total.

Many thanks

**Comment by anvaka** [comment]
The algorithm for finding all connected components is straightforward. We perform BFS/DFS search from each node and mark visited nodes with a given label. If node was not labeled after BFS/DFS is completed, it means we found a new component. So we create a new label and keep iterating.

Here is a code with example: https://github.com/anvaka/ngraph.graph/blob/master/examples/findConnectedComponents.js

**Comment by githubuser3141** [comment]
Thank you very much for this and all your work!
