### ISSUE TITLE
getlink for multigraph

### ISSUE THREAD

**Issue by lewis500** [anvaka/ngraph.graph#19]
From reading the code, it seems that `getLlink(a,b)` just returns the first link it finds between `a` and `b.` But if you have the `multigraph` option set to true, there may be multiple links.
The reason I ask is I am using ngraph.path on a multigraph, and I want to get which particular links are being used.

**Comment by anvaka** [comment]
You can use `forEachLinkedNode()` for this. For example, here is a function that should return all links:

``` js
function getAllMultiLinks(graph, fromId, toId) {
  let multiLinks = [];

  graph.forEachLinkedNode(fromId, function(otherNode, link) {
    if (otherNode.id === toId) multiLinks.push(link);
  }, /* oriented = */ true);

  return multiLinks;
}
```

Would this work?
