### ISSUE TITLE
Updating beginUpdate to point to enterModificationReal

### ISSUE THREAD

**Issue by swilly22** [anvaka/ngraph.graph#2]
createGraph sets beginUpdate to enterModification,

When calling the 'on' function:
enterModification = enterModificationReal, gets executed, BUT beginUpdate doesn't get updated, the function still holds the original value of enterModification which is noop.

tested on Chrome 41.0.2272.

the following example illustrates the problem:
var c = function() { console.log('c'); };
var b = c;
var a = b;

b = function() { console.log('b'); };

a(); // Prints 'c'
Would like a to print 'b'.

**Comment by anvaka** [comment]
Thanks for reporting this! Should be fixed in version `0.0.11`
