### ISSUE TITLE
forEachNode typing not quite correct

### ISSUE THREAD

**Issue by lordnox** [anvaka/ngraph.graph#25]
As the forEachNode loop will stop when returning `true` https://github.com/anvaka/ngraph.graph/blob/b5e768a57620255437e3b7ab2a44bb98265ce285/index.js#L520-L524

The typing of forEachNode should be amended:
```typescript
/** To stop the iteration return true in the callback */
forEachNode: (callbackPerNode: (node: Node<NodeData>) => void | undefined | null | boolean) => void
```

This would allow the use of the function as described in the readme:
```
g.forEachNode(function(node){
    console.log(node.id, node.data);
});
```

Typescript will fail here as the return value is `undefined` and not `boolean`

**Comment by anvaka** [comment]
Tobias, thank you for noticing it and fixing it!

Your fix should be available starting from `v19.0.1`
