### ISSUE TITLE
Exiting `ForEach` family of functions

### ISSUE THREAD

**Issue by nemosmithasf** [anvaka/ngraph.graph#31]
Does the returning `true` to exit only work for `.forEachNode` and not `forEachLink` and `forEachLinkedNode`? 

That seems to be what the typescript file suggests, but it seems like a rather odd discrepancy between functions of the same family.

PS: Also, I don't believe this feature is documented in the README

**Comment by anvaka** [comment]
I agree, thanks for pointing out. `forEachLinkedNode()` can exist fast, `forEachLink()` cannot. Need to update this.

**Comment by anvaka** [comment]
I believe this was fixed here https://github.com/anvaka/ngraph.graph/blob/e0a35bf3cf94a5a895ef7e2a235cdf772b6d07a7/index.js#L464 

Added a few tests to confirm as well.

**Comment by nemosmithasf** [comment]
@anvaka would you be able to update the version hosted on NPM to reflect the update?

**Comment by nala-two** [comment]
Agree with @nemosmithasf - the NPM version doesn't currently include this change

**Comment by anvaka** [comment]
Published now under major (breaks backward compatibility) change: `v20`. Please let me know if you run into any issues so I can update the modules
