### ISSUE TITLE
inconsistent "replacing" behaviour between `addNode` and `addLink`

### ISSUE THREAD

**Issue by nemosmithasf** [anvaka/ngraph.graph#33]
It seems that `addNode` will overwrite and replace any existing nodes, `addLink` however does not do this.

Perhaps you can consider implementing this for the sake of consistency between the methods.

**Comment by anvaka** [comment]
This should be fixed in the repository and will be published as `v20`.  See the [changelog](https://github.com/anvaka/ngraph.graph/blob/master/CHANGELOG.md) for details.
