### ISSUE TITLE
`Node.links === null` when there are no links, inconsistent with type definition

### ISSUE THREAD

**Issue by nemosmithasf** [anvaka/ngraph.graph#35]
Type definition for `Node.links` seems to suggest that we return an empty array when there's no links.

The actual behaviour is returning `Node.links === null`.

**Comment by anvaka** [comment]
yes! That's a good catch. We don't create links until truly necessary, as this can causes significant increase of memory usage for the graphs with many isolated nodes.

**Comment by anvaka** [comment]
btw, this was fixed a while back: https://github.com/anvaka/ngraph.graph/blob/1659251bb3d7811e7c377ba4361b60039fd6c24d/index.d.ts#L56
