### ISSUE TITLE
Update data property of Node

### ISSUE THREAD

**Issue by DeveloperInProgress** [anvaka/ngraph.graph#46]
Is it possible to reassign a different value to `Node.data` property after initial assignment?

**Comment by DeveloperInProgress** [comment]
I see that `addNode()` simply updates the node data if a node with given NodeId already exists: https://github.com/anvaka/ngraph.graph/blob/c9a891baeaa6029ee5acfd6ee7955899396a7bc6/index.js#L309

this wouldn't alter the links from/to the node would it ?

**Comment by anvaka** [comment]
No, links are stored separately
