### ISSUE TITLE
Code in bundle does not match source

### ISSUE THREAD

**Issue by fecorreiabr** [anvaka/ngraph.graph#47]
The code in dist/ngraph.graph.js for v20.0.0 does not seem to match its source.

Comparison of lines 53-57 below (v20.0.0).

dist/ngraph.graph.js:
```
var nodes = new Map();
  var links = [],
    // Hash of multi-edges. Used to track ids of edges between same nodes
    multiEdges = {},
    suspendEvents = 0,
```

index.js:
```
var nodes = new Map(); // nodeId => Node
  var links = new Map(); // linkId => Link
    // Hash of multi-edges. Used to track ids of edges between same nodes
  var multiEdges = {};
  var suspendEvents = 0;
```

It looks like the code in the bundle actually matches the index.js of the previous version (v19.1.0).

**Comment by anvaka** [comment]
Thank you for catching this. Rebuilt and published it here https://github.com/anvaka/ngraph.graph/commit/869e035d546ce39a557e0496d058905f00c11da3

Should be available here https://unpkg.com/ngraph.graph@20.0.1/dist/ngraph.graph.min.js
