### ISSUE TITLE
Add hasNode function

### ISSUE THREAD

**Issue by gimyboya** [anvaka/ngraph.graph#5]
As the title describes a `hasNode` function is missing and it is one of the basic building blocks of a graph data structure.

it would be great to implement one

**Comment by anvaka** [comment]
I agree. The reason `hasNode` isn't there yet - just because `getNode()` would return falsy value if no node is present, and I always used that. But I think you are right. We need `hasNode()` method to make API symmetrical with `hasLink`, and more intuitive.

**Comment by gimyboya** [comment]
yes that's what i am using right now after reading a portion of your code but as you say a `hasNode` function is a must!

**Comment by gimyboya** [comment]
Awesome! just to make sure the operation complexity is what exactly i think there was a typo...
and how do i upgrade this to mt vivaGraph now ?
also i have sent you an email
