### ISSUE TITLE
Extending ngraph.graph for visibility graph

### ISSUE THREAD

**Issue by rowanwins** [anvaka/ngraph.graph#6]
Gday @anvaka 

Im looking at adopting ngraph.graph for my [visibility graph algorithm](https://rowanwins.github.io/visibility-graph/index.html) - basically my library reads in polygons and returns a graph showing other visible nodes in the graph, this can be used for path finding by vessels (eg finding me the shortest path but avoid sailing on land!).

My library is functional but I think it would be nice to hook into the ngraph ecosystem you've created which has some neat features like saving graphs etc. 

I'm trying to work out the best way to extend ngraph.graph, eg im envisaging something that looks like
````
var createGraph = require('ngraph.graph');
var g = createGraph();
g.loadPolygons(somepolygons);

// or

var g = require('ngraph.vis-graph').createGraph();
g.loadPolygons(somepolygons);
 
````

Any tips as to which of your repos might provide a good example of extending things in this sort of manner? I'm open to any ideas you might have as the best way to do this.

Thanks,
Rowan

**Comment by anvaka** [comment]
Hello @rowanwins !

I'd create a separate module, which exports one function:

``` js
module.exports = polygonsToVisibilityGraph;

/**
 * Converts set of polygons to a visibility graph 
 * 
 * @param {...} polygonsSet - ...
 * @param {ngraph.graph} appendToGraph - optional argument, if passed the visibility graph is
 *   appended here.
 *
 * @returns instance of ngrpah.graph, which corresponds to polygons visibility graph.
 */
function polygonsToVisibilityGraph(polygonsSet, appendToGraph) {
  // ...
}
```

Here is an example with `dot` loader: https://github.com/anvaka/ngraph.fromdot/blob/master/index.js

Does this make sense?

**Comment by rowanwins** [comment]
Yeah I think so, thanks @anvaka 

I think I'll also need to hook into the event listeners, so for example while the initial set of polygons might be relatively static (eg country borders), I'll need to allow users to add a new node to the graph (representing a start or end point), and when that happens I'll need to respond and calculate the edges for that node using my algorithm.

Anyway I'll have a play around and see what I can come up with, if I get stuck I might sing out otherwise hopefully I'll be reporting back in a few weeks with a successful implementation!

Also thanks for your awesome work on the library, it's really clearly laid out and as someone new to graphs it has helped me get a better handle on them!

**Comment by anvaka** [comment]
Good luck with the implementation! Looking forward to hearing back from you.
