### ISSUE TITLE
Directed Graph Support

### ISSUE THREAD

**Issue by econ24** [anvaka/ngraph.graph#7]
Is there any way to force the graph and pathfinder to obey link directions? The following example illustrates the problem. The path finder finds a path from "A" to "E" as expected. Unfortunately, it also finds a path from "E" to "A" even though no directed links exists between many of the nodes in this direction. Additionally, where links do exist ("C1" -> "B" and "C2" -> "B"), the given weights are ignored.

const createGraph = require('ngraph.graph');
const pathFinders = require("ngraph.path");

let graph = createGraph();

graph.addLink("A", "B", { weight: 1 });

graph.addLink("B", "C1", { weight: 1 });
graph.addLink("B", "C2", { weight: 5 });
graph.addLink("C1", "B", { weight: 5 });
graph.addLink("C2", "B", { weight: 1 });

graph.addLink("C1", "D", { weight: 1 });
graph.addLink("C2", "D", { weight: 1 });

graph.addLink("D", "E", { weight: 1 });
let finder = pathFinders.aStar(graph, {
    distance: (fromNode, toNode, link) => link.data.weight
});

const test1 = finder.find("A", "E").reverse();
const test2 = finder.find("E", "A").reverse();

console.log("TEST 1");
test1.forEach(p => console.log("id:",p.id));

console.log("\nTEST 2");
test2.forEach(p => console.log("id:",p.id));

OUTPUT:
TEST 1
id: A
id: B
id: C1
id: D
id: E

TEST 2
id: E
id: D
id: C1
id: B
id: A

**Comment by econ24** [comment]
That seemed to do the trick, thanks a lot!

**Comment by vincenzopalazzo** [comment]
Hello @anvaka,
If I don't use the ngraph.path is it possible to render a Directed Graph?
